In [ ]:
#resnet 50 analysis

In [1]:
%pip install tensorflow
%pip install scikit-learn


Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.


In [6]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from sklearn.metrics import classification_report, confusion_matrix
from tensorflow.keras.applications.resnet50 import preprocess_input as resnet50_preprocess_input

# Load the saved model
model = tf.keras.models.load_model('C:/Users/swadh/OneDrive/Desktop/crimedetection/resnet.h5')

# Define the test data generator
IMAGE_RESIZE = (240, 320)
BATCH_SIZE_TESTING = 32

def preprocess_input(img):
    # Apply ResNet50 specific preprocessing
    img = resnet50_preprocess_input(img)
    return img


test_data_generator = ImageDataGenerator(preprocessing_function=preprocess_input)

test_generator = test_data_generator.flow_from_directory(
    r'C:\Users\swadh\OneDrive\Desktop\crimedetection',  # Path to the parent directory of test_crime and test_normal
    target_size=IMAGE_RESIZE,
    batch_size=BATCH_SIZE_TESTING,
    class_mode='binary',
    classes=['test_crime', 'test_normal'],  # Ensure these match your folder names
    shuffle=False
)


Found 556 images belonging to 2 classes.


In [7]:
# Predict the labels for the test data
predictions = model.predict(test_generator, steps=test_generator.samples // test_generator.batch_size + 1)
predicted_classes = np.where(predictions > 0.5, 1, 0)

# Get the true labels
true_classes = test_generator.classes
class_labels = list(test_generator.class_indices.keys())

# Generate the classification report
report = classification_report(true_classes, predicted_classes, target_names=class_labels)
print(report)

# Generate the confusion matrix
conf_matrix = confusion_matrix(true_classes, predicted_classes)
print(conf_matrix)


c:\Users\swadh\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\trainers\data_adapters\py_dataset_adapter.py:121: UserWarning: Your `PyDataset` class should call `super().__init__(**kwargs)` in its constructor. `**kwargs` can include `workers`, `use_multiprocessing`, `max_queue_size`. Do not pass these arguments to `fit()`, as they will be ignored.
  self._warn_if_super_not_called()


18/18 ━━━━━━━━━━━━━━━━━━━━ 43s 2s/step
              precision    recall  f1-score   support

  test_crime       0.98      0.97      0.98       330
 test_normal       0.95      0.98      0.97       226

    accuracy                           0.97       556
   macro avg       0.97      0.97      0.97       556
weighted avg       0.97      0.97      0.97       556

[[319  11]
 [  5 221]]


In [ ]:
#vgg16 model analysis

In [9]:
from tensorflow.keras.applications.vgg16 import VGG16, preprocess_input as vgg16_preprocess_input
def preprocess_input(img):
    img = vgg16_preprocess_input(img)
    return img

# Load the saved model
model = tf.keras.models.load_model('C:/Users/swadh/OneDrive/Desktop/crimedetection/vgg16.h5')

# Define the test data generator
IMAGE_RESIZE = (240, 320)
BATCH_SIZE_TESTING = 32




test_data_generator = ImageDataGenerator(preprocessing_function=preprocess_input)

test_generator = test_data_generator.flow_from_directory(
    r'C:\Users\swadh\OneDrive\Desktop\crimedetection',  # Path to the parent directory of test_crime and test_normal
    target_size=IMAGE_RESIZE,
    batch_size=BATCH_SIZE_TESTING,
    class_mode='binary',
    classes=['test_crime', 'test_normal'],  # Ensure these match your folder names
    shuffle=False
)


Found 556 images belonging to 2 classes.


In [10]:
# Predict the labels for the test data
predictions = model.predict(test_generator, steps=test_generator.samples // test_generator.batch_size + 1)
predicted_classes = np.where(predictions > 0.5, 1, 0)

# Get the true labels
true_classes = test_generator.classes
class_labels = list(test_generator.class_indices.keys())

# Generate the classification report
report = classification_report(true_classes, predicted_classes, target_names=class_labels)
print(report)

# Generate the confusion matrix
conf_matrix = confusion_matrix(true_classes, predicted_classes)
print(conf_matrix)


c:\Users\swadh\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\trainers\data_adapters\py_dataset_adapter.py:121: UserWarning: Your `PyDataset` class should call `super().__init__(**kwargs)` in its constructor. `**kwargs` can include `workers`, `use_multiprocessing`, `max_queue_size`. Do not pass these arguments to `fit()`, as they will be ignored.
  self._warn_if_super_not_called()


18/18 ━━━━━━━━━━━━━━━━━━━━ 107s 6s/step
              precision    recall  f1-score   support

  test_crime       0.97      0.98      0.98       330
 test_normal       0.97      0.96      0.97       226

    accuracy                           0.97       556
   macro avg       0.97      0.97      0.97       556
weighted avg       0.97      0.97      0.97       556

[[324   6]
 [  9 217]]


In [ ]:
#vgg19 model analysis

In [11]:

from tensorflow.keras.applications.vgg19 import VGG19, preprocess_input as vgg19_preprocess_input
# Define the preprocessing function for VGG19
def preprocess_input(img):
    img = vgg19_preprocess_input(img)
    return img

In [12]:

# Load the saved model
model = tf.keras.models.load_model('C:/Users/swadh/OneDrive/Desktop/crimedetection/vgg19.h5')

# Define the test data generator
IMAGE_RESIZE = (240, 320)
BATCH_SIZE_TESTING = 32

test_data_generator = ImageDataGenerator(preprocessing_function=preprocess_input)

test_generator = test_data_generator.flow_from_directory(
    r'C:\Users\swadh\OneDrive\Desktop\crimedetection',  # Path to the parent directory of test_crime and test_normal
    target_size=IMAGE_RESIZE,
    batch_size=BATCH_SIZE_TESTING,
    class_mode='binary',
    classes=['test_crime', 'test_normal'],  # Ensure these match your folder names
    shuffle=False
)


Found 556 images belonging to 2 classes.


In [13]:
# Predict the labels for the test data
predictions = model.predict(test_generator, steps=test_generator.samples // test_generator.batch_size + 1)
predicted_classes = np.where(predictions > 0.5, 1, 0)

# Get the true labels
true_classes = test_generator.classes
class_labels = list(test_generator.class_indices.keys())

# Generate the classification report
report = classification_report(true_classes, predicted_classes, target_names=class_labels)
print(report)

# Generate the confusion matrix
conf_matrix = confusion_matrix(true_classes, predicted_classes)
print(conf_matrix)


c:\Users\swadh\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\trainers\data_adapters\py_dataset_adapter.py:121: UserWarning: Your `PyDataset` class should call `super().__init__(**kwargs)` in its constructor. `**kwargs` can include `workers`, `use_multiprocessing`, `max_queue_size`. Do not pass these arguments to `fit()`, as they will be ignored.
  self._warn_if_super_not_called()


18/18 ━━━━━━━━━━━━━━━━━━━━ 147s 8s/step
              precision    recall  f1-score   support

  test_crime       0.98      0.97      0.98       330
 test_normal       0.96      0.97      0.96       226

    accuracy                           0.97       556
   macro avg       0.97      0.97      0.97       556
weighted avg       0.97      0.97      0.97       556

[[321   9]
 [  7 219]]


In [ ]:
#alexnet model analysis

In [15]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from sklearn.metrics import classification_report, confusion_matrix

# Load the saved model
model = tf.keras.models.load_model('C:/Users/swadh/OneDrive/Desktop/crimedetection/alexnet.h5')

# Define the test data generator
IMAGE_RESIZE = (240, 320)
BATCH_SIZE = 32

test_data_generator = ImageDataGenerator(rescale=1./255)

# Create a generator for the test data
test_generator = test_data_generator.flow_from_directory(
    r'C:\Users\swadh\OneDrive\Desktop\crimedetection',
    target_size=IMAGE_RESIZE,
    batch_size=BATCH_SIZE,
    class_mode='binary',
    classes=['test_crime', 'test_normal'],
    shuffle=False
)

# Evaluate the model on the test data
evaluation = model.evaluate(test_generator)
print(f"Test Loss: {evaluation[0]}, Test Accuracy: {evaluation[1]}")

# Predict the test data
test_generator.reset()
preds = model.predict(test_generator, steps=test_generator.samples // BATCH_SIZE + 1)
predicted_classes = (preds > 0.5).astype("int32").flatten()

# Get the ground truth
true_classes = test_generator.classes
class_labels = list(test_generator.class_indices.keys())

# Print classification report
report = classification_report(true_classes, predicted_classes, target_names=class_labels)
print(report)

# Compute confusion matrix
conf_matrix = confusion_matrix(true_classes, predicted_classes)
print(conf_matrix)




Found 556 images belonging to 2 classes.


c:\Users\swadh\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\trainers\data_adapters\py_dataset_adapter.py:121: UserWarning: Your `PyDataset` class should call `super().__init__(**kwargs)` in its constructor. `**kwargs` can include `workers`, `use_multiprocessing`, `max_queue_size`. Do not pass these arguments to `fit()`, as they will be ignored.
  self._warn_if_super_not_called()


18/18 ━━━━━━━━━━━━━━━━━━━━ 7s 362ms/step - accuracy: 0.8890 - loss: 0.2783
Test Loss: 0.3514704704284668, Test Accuracy: 0.8381295204162598
18/18 ━━━━━━━━━━━━━━━━━━━━ 7s 377ms/step
              precision    recall  f1-score   support

  test_crime       0.81      0.94      0.87       330
 test_normal       0.89      0.69      0.78       226

    accuracy                           0.84       556
   macro avg       0.85      0.81      0.82       556
weighted avg       0.85      0.84      0.83       556

[[311  19]
 [ 71 155]]


In [16]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from sklearn.metrics import classification_report, confusion_matrix

# Load the saved model
model = tf.keras.models.load_model('C:/Users/swadh/OneDrive/Desktop/crimedetection/self.h5')

# Define the test data generator
IMAGE_RESIZE = (240, 320)
BATCH_SIZE = 32

test_data_generator = ImageDataGenerator(rescale=1./255)

# Create a generator for the test data
test_generator = test_data_generator.flow_from_directory(
    r'C:\Users\swadh\OneDrive\Desktop\crimedetection',
    target_size=IMAGE_RESIZE,
    batch_size=BATCH_SIZE,
    class_mode='binary',
    classes=['test_crime', 'test_normal'],
    shuffle=False
)

# Evaluate the model on the test data
evaluation = model.evaluate(test_generator)
print(f"Test Loss: {evaluation[0]}, Test Accuracy: {evaluation[1]}")

# Predict the test data
test_generator.reset()
preds = model.predict(test_generator, steps=test_generator.samples // BATCH_SIZE + 1)
predicted_classes = (preds > 0.5).astype("int32").flatten()

# Get the ground truth
true_classes = test_generator.classes
class_labels = list(test_generator.class_indices.keys())

# Print classification report
report = classification_report(true_classes, predicted_classes, target_names=class_labels)
print(report)

# Compute confusion matrix
conf_matrix = confusion_matrix(true_classes, predicted_classes)
print(conf_matrix)



Found 556 images belonging to 2 classes.


c:\Users\swadh\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\trainers\data_adapters\py_dataset_adapter.py:121: UserWarning: Your `PyDataset` class should call `super().__init__(**kwargs)` in its constructor. `**kwargs` can include `workers`, `use_multiprocessing`, `max_queue_size`. Do not pass these arguments to `fit()`, as they will be ignored.
  self._warn_if_super_not_called()


18/18 ━━━━━━━━━━━━━━━━━━━━ 6s 330ms/step - accuracy: 0.8800 - loss: 0.2651
Test Loss: 0.24591591954231262, Test Accuracy: 0.8902877569198608
18/18 ━━━━━━━━━━━━━━━━━━━━ 6s 312ms/step
              precision    recall  f1-score   support

  test_crime       0.92      0.90      0.91       330
 test_normal       0.85      0.88      0.87       226

    accuracy                           0.89       556
   macro avg       0.89      0.89      0.89       556
weighted avg       0.89      0.89      0.89       556

[[296  34]
 [ 27 199]]
